name: Workflow Conclusion Action

description: GitHub action to get workflow conclusion.

author: technote-space

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  TARGET_RUN_ID:
    description: Target run id
    default: ${{ github.run_id }}
    required: true
  SET_ENV_NAME:
    description: Env name
    required: false
    default: WORKFLOW_CONCLUSION
  FALLBACK_CONCLUSION:
    description: Fallback conclusion
    required: false
    default: skipped
  GITHUB_API_URL:
    description: GITHUB API URL
    required: false
    default: https://api.github.com

outputs:
  conclusion:
    description: Workflow conclusion

branding:
  icon: 'check-circle'
  color: 'green'

runs:
  using: node12
  main: lib/main.js
